-- MySQL Script generated by MySQL Workbench
-- Sun Oct  5 10:49:35 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_tecnovera
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_tecnovera`;
CREATE SCHEMA IF NOT EXISTS `db_tecnovera` DEFAULT CHARACTER SET utf8;
USE `db_tecnovera`;

-- -----------------------------------------------------
-- Table `db_tecnovera`.`TIPO_DOCUMENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tecnovera`.`TIPO_DOCUMENTO`;
CREATE TABLE IF NOT EXISTS `db_tecnovera`.`TIPO_DOCUMENTO` (
  `IdTipoDocumento` INT NOT NULL AUTO_INCREMENT,
  `NombreDocumento` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`IdTipoDocumento`)
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_tecnovera`.`PAIS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tecnovera`.`PAIS`;
CREATE TABLE IF NOT EXISTS `db_tecnovera`.`PAIS` (
  `id_pais` INT NOT NULL AUTO_INCREMENT,
  `nombre_pais` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_pais`)
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_tecnovera`.`DEPARTAMENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tecnovera`.`DEPARTAMENTO`;
CREATE TABLE IF NOT EXISTS `db_tecnovera`.`DEPARTAMENTO` (
  `id_departamento` INT NOT NULL AUTO_INCREMENT,
  `nombre_departamento` VARCHAR(50) NOT NULL,
  `id_pais` INT NOT NULL,
  PRIMARY KEY (`id_departamento`),
  INDEX `fk_DEPARTAMENTO_PAIS1_idx` (`id_pais` ASC),
  CONSTRAINT `fk_DEPARTAMENTO_PAIS1`
    FOREIGN KEY (`id_pais`)
    REFERENCES `db_tecnovera`.`PAIS` (`id_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_tecnovera`.`PROVINCIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tecnovera`.`PROVINCIA`;
CREATE TABLE IF NOT EXISTS `db_tecnovera`.`PROVINCIA` (
  `id_provincia` INT NOT NULL AUTO_INCREMENT,
  `nombre_provincia` VARCHAR(50) NOT NULL,
  `id_departamento` INT NOT NULL,
  PRIMARY KEY (`id_provincia`),
  INDEX `fk_PROVINCIA_DEPARTAMENTO1_idx` (`id_departamento` ASC),
  CONSTRAINT `fk_PROVINCIA_DEPARTAMENTO1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `db_tecnovera`.`DEPARTAMENTO` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_tecnovera`.`DISTRITO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tecnovera`.`DISTRITO`;
CREATE TABLE IF NOT EXISTS `db_tecnovera`.`DISTRITO` (
  `id_distrito` INT NOT NULL AUTO_INCREMENT,
  `nombre_distrito` VARCHAR(50) NOT NULL,
  `id_provincia` INT NOT NULL,
  PRIMARY KEY (`id_distrito`),
  INDEX `fk_DISTRITO_PROVINCIA1_idx` (`id_provincia` ASC),
  CONSTRAINT `fk_DISTRITO_PROVINCIA1`
    FOREIGN KEY (`id_provincia`)
    REFERENCES `db_tecnovera`.`PROVINCIA` (`id_provincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_tecnovera`.`CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tecnovera`.`CLIENTE`;
CREATE TABLE IF NOT EXISTS `db_tecnovera`.`CLIENTE` (
  `IdCliente` INT NOT NULL AUTO_INCREMENT,
  `IdTipoDocumento` INT NOT NULL,
  `NumeroDocumento` VARCHAR(15) NOT NULL,
  `IdDistrito` INT NOT NULL,
  `NombreCliente` VARCHAR(85) NOT NULL,
  `ApellidosCliente` VARCHAR(85) NOT NULL,
  `Direccion` VARCHAR(100) NOT NULL,
  `Telefono` VARCHAR(9) NOT NULL,
  `Correo` VARCHAR(100) NULL,
  PRIMARY KEY (`IdCliente`),
  UNIQUE INDEX `DNI_UNIQUE` (`NumeroDocumento` ASC),
  INDEX `fk_CLIENTE_TIPO_DOCUMENTO1_idx` (`IdTipoDocumento` ASC),
  INDEX `fk_CLIENTE_DISTRITO1_idx` (`IdDistrito` ASC),
  CONSTRAINT `fk_CLIENTE_TIPO_DOCUMENTO1`
    FOREIGN KEY (`IdTipoDocumento`)
    REFERENCES `db_tecnovera`.`TIPO_DOCUMENTO` (`IdTipoDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTE_DISTRITO1`
    FOREIGN KEY (`IdDistrito`)
    REFERENCES `db_tecnovera`.`DISTRITO` (`id_distrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_tecnovera`.`MARCA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tecnovera`.`MARCA`;
CREATE TABLE IF NOT EXISTS `db_tecnovera`.`MARCA` (
  `IdMarca` INT NOT NULL AUTO_INCREMENT,
  `NombreMarca` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`IdMarca`)
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_tecnovera`.`MODELO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tecnovera`.`MODELO`;
CREATE TABLE IF NOT EXISTS `db_tecnovera`.`MODELO` (
  `IdModelo` INT NOT NULL AUTO_INCREMENT,
  `NombreModelo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`IdModelo`)
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_tecnovera`.`CATEGORIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tecnovera`.`CATEGORIA`;
CREATE TABLE IF NOT EXISTS `db_tecnovera`.`CATEGORIA` (
  `IdCategoria` INT NOT NULL AUTO_INCREMENT,
  `NombreCategoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdCategoria`)
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_tecnovera`.`PRODUCTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tecnovera`.`PRODUCTO`;
CREATE TABLE IF NOT EXISTS `db_tecnovera`.`PRODUCTO` (
  `IdProducto` INT NOT NULL AUTO_INCREMENT,
  `NombreProducto` VARCHAR(45) NOT NULL,
  `IdCategoria` INT NOT NULL,
  `IdMarca` INT NOT NULL,
  `IdModelo` INT NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Precio` DOUBLE NOT NULL,
  `Stock` INT NOT NULL,
  `Garantia` INT NOT NULL COMMENT 'garantia en meses',
  `EstadoProducto` TINYINT(1) NOT NULL,
  PRIMARY KEY (`IdProducto`),
  INDEX `fk_PRODUCTO_MARCA1_idx` (`IdMarca` ASC),
  INDEX `fk_PRODUCTO_MODELO1_idx` (`IdModelo` ASC),
  INDEX `fk_PRODUCTO_CATEGORIA1_idx` (`IdCategoria` ASC),
  CONSTRAINT `fk_PRODUCTO_MARCA1`
    FOREIGN KEY (`IdMarca`)
    REFERENCES `db_tecnovera`.`MARCA` (`IdMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCTO_MODELO1`
    FOREIGN KEY (`IdModelo`)
    REFERENCES `db_tecnovera`.`MODELO` (`IdModelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCTO_CATEGORIA1`
    FOREIGN KEY (`IdCategoria`)
    REFERENCES `db_tecnovera`.`CATEGORIA` (`IdCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_tecnovera`.`TIPO_PAGO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tecnovera`.`TIPO_PAGO`;
CREATE TABLE IF NOT EXISTS `db_tecnovera`.`TIPO_PAGO` (
  `IdTipoPago` INT NOT NULL AUTO_INCREMENT,
  `TipoPago` VARCHAR(45) NOT NULL COMMENT 'tipo de pago: tarjeta, efectivo, transferencia, yape, plin, otros.',
  PRIMARY KEY (`IdTipoPago`)
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_tecnovera`.`PAGO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tecnovera`.`PAGO`;
CREATE TABLE IF NOT EXISTS `db_tecnovera`.`PAGO` (
  `IdPago` INT NOT NULL AUTO_INCREMENT,
  `IdTipoPago` INT NOT NULL,
  `FechaPago` DATE NOT NULL,
  `Monto` DOUBLE NOT NULL,
  `Estado` VARCHAR(45) NOT NULL COMMENT 'Estado: aprobado, rechazado, pendiente',
  PRIMARY KEY (`IdPago`),
  INDEX `fk_PAGO_TIPO_PAGO1_idx` (`IdTipoPago` ASC),
  CONSTRAINT `fk_PAGO_TIPO_PAGO1`
    FOREIGN KEY (`IdTipoPago`)
    REFERENCES `db_tecnovera`.`TIPO_PAGO` (`IdTipoPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_tecnovera`.`CARGO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tecnovera`.`CARGO`;
CREATE TABLE IF NOT EXISTS `db_tecnovera`.`CARGO` (
  `IdCargo` INT NOT NULL AUTO_INCREMENT,
  `NombreCargo` VARCHAR(85) NOT NULL COMMENT 'Ventas, almacen, Administracion, Soporte Tecnico, Gerencia',
  `EstadoCargo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`IdCargo`)
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_tecnovera`.`TIPO_EMPLEADO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tecnovera`.`TIPO_EMPLEADO`;
CREATE TABLE IF NOT EXISTS `db_tecnovera`.`TIPO_EMPLEADO` (
  `IdTipoEmpleado` INT NOT NULL AUTO_INCREMENT,
  `TipoEmpleado` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`IdTipoEmpleado`)
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_tecnovera`.`PROFESION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tecnovera`.`PROFESION`;
CREATE TABLE IF NOT EXISTS `db_tecnovera`.`PROFESION` (
  `IdProfesion` INT NOT NULL AUTO_INCREMENT,
  `nombre_profesion` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`IdProfesion`)
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_tecnovera`.`EMPLEADO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tecnovera`.`EMPLEADO`;
CREATE TABLE IF NOT EXISTS `db_tecnovera`.`EMPLEADO` (
  `IdEmpleado` INT NOT NULL AUTO_INCREMENT,
  `IdTipoDocumento` INT NOT NULL,
  `NumeroDocumento` VARCHAR(15) NOT NULL,
  `IdDistrito` INT NOT NULL,
  `NombreEmpleado` VARCHAR(100) NOT NULL,
  `ApellidosEmpleado` VARCHAR(100) NOT NULL,
  `FechaContrato` DATE NOT NULL,
  `IdTipoEmpleado` INT NOT NULL,
  `IdProfesion` INT NOT NULL,
  `IdCargo` INT NOT NULL,
  `Salario` DOUBLE NOT NULL,
  `CorreoEmpleado` VARCHAR(150) NOT NULL,
  `Telefono1` VARCHAR(20) NOT NULL,
  `Telefono2` VARCHAR(20) NULL,
  `EstadoEmpleado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`IdEmpleado`),
  INDEX `fk_EMPLEADO_CARGO1_idx` (`IdCargo` ASC),
  INDEX `fk_EMPLEADO_TIPO_DOCUMENTO1_idx` (`IdTipoDocumento` ASC),
  INDEX `fk_EMPLEADO_TIPO_EMPLEADO1_idx` (`IdTipoEmpleado` ASC),
  INDEX `fk_EMPLEADO_DISTRITO1_idx` (`IdDistrito` ASC),
  INDEX `fk_EMPLEADO_PROFESION1_idx` (`IdProfesion` ASC),
  CONSTRAINT `fk_EMPLEADO_CARGO1`
    FOREIGN KEY (`IdCargo`)
    REFERENCES `db_tecnovera`.`CARGO` (`IdCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPLEADO_TIPO_DOCUMENTO1`
    FOREIGN KEY (`IdTipoDocumento`)
    REFERENCES `db_tecnovera`.`TIPO_DOCUMENTO` (`IdTipoDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPLEADO_TIPO_EMPLEADO1`
    FOREIGN KEY (`IdTipoEmpleado`)
    REFERENCES `db_tecnovera`.`TIPO_EMPLEADO` (`IdTipoEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPLEADO_DISTRITO1`
    FOREIGN KEY (`IdDistrito`)
    REFERENCES `db_tecnovera`.`DISTRITO` (`id_distrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPLEADO_PROFESION1`
    FOREIGN KEY (`IdProfesion`)
    REFERENCES `db_tecnovera`.`PROFESION` (`IdProfesion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_tecnovera`.`SUCURSAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tecnovera`.`SUCURSAL`;
CREATE TABLE IF NOT EXISTS `db_tecnovera`.`SUCURSAL` (
  `IdSucursal` INT NOT NULL AUTO_INCREMENT,
  `NombreSucursal` VARCHAR(100) NOT NULL,
  `DireccionSucursal` VARCHAR(100) NOT NULL,
  `TelefonoSucursal` VARCHAR(20) NOT NULL,
  `OtroTelefono` VARCHAR(20) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Responsable` VARCHAR(45) NOT NULL,
  `Estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`IdSucursal`)
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_tecnovera`.`ALMACEN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tecnovera`.`ALMACEN`;
CREATE TABLE IF NOT EXISTS `db_tecnovera`.`ALMACEN` (
  `IdAlmacen` INT NOT NULL AUTO_INCREMENT,
  `IdSucursal` INT NOT NULL,
  `NombreAlmacen` VARCHAR(100) NOT NULL,
  `Ubicacion` VARCHAR(120) NOT NULL COMMENT 'Ubicacion exacta',
  `Ciudad` VARCHAR(50) NOT NULL,
  `Capacidad` INT NOT NULL,
  `Encargado` VARCHAR(150) NOT NULL,
  `TelefonoContacto` VARCHAR(20) NOT NULL,
  `Estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`IdAlmacen`),
  INDEX `fk_ALMACEN_SUCURSAL1_idx` (`IdSucursal` ASC),
  CONSTRAINT `fk_ALMACEN_SUCURSAL1`
    FOREIGN KEY (`IdSucursal`)
    REFERENCES `db_tecnovera`.`SUCURSAL` (`IdSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_tecnovera`.`INVENTARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tecnovera`.`INVENTARIO`;
CREATE TABLE IF NOT EXISTS `db_tecnovera`.`INVENTARIO` (
  `IdInventario` INT NOT NULL AUTO_INCREMENT,
  `IdProducto` INT NOT NULL,
  `StockInicial` INT NOT NULL,
  `UltimaActualizacion` DATE NOT NULL,
  `IdAlmacen` INT NOT NULL,
  PRIMARY KEY (`IdInventario`),
  INDEX `fk_INVENTARIO_PRODUCTO1_idx` (`IdProducto` ASC),
  INDEX `fk_INVENTARIO_ALMACEN1_idx` (`IdAlmacen` ASC),
  CONSTRAINT `fk_INVENTARIO_PRODUCTO1`
    FOREIGN KEY (`IdProducto`)
    REFERENCES `db_tecnovera`.`PRODUCTO` (`IdProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INVENTARIO_ALMACEN1`
    FOREIGN KEY (`IdAlmacen`)
    REFERENCES `db_tecnovera`.`ALMACEN` (`IdAlmacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_tecnovera`.`PROVEEDOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tecnovera`.`PROVEEDOR`;
CREATE TABLE IF NOT EXISTS `db_tecnovera`.`PROVEEDOR` (
  `IdProveedor` INT NOT NULL AUTO_INCREMENT,
  `RazonSocial` VARCHAR(80) NOT NULL,
  `RUC` VARCHAR(30) NOT NULL,
  `Contacto` VARCHAR(20) NOT NULL,
  `Contacto2` VARCHAR(20) NOT NULL,
  `CorreoElectronico` VARCHAR(150) NOT NULL,
  `DireccionProveedor` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`IdProveedor`)
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_tecnovera`.`COMPRA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tecnovera`.`COMPRA`;
CREATE TABLE IF NOT EXISTS `db_tecnovera`.`COMPRA` (
  `IdCompra` INT NOT NULL AUTO_INCREMENT,
  `IdProveedor` INT NOT NULL,
  `IdEmpleado` INT NOT NULL,
  `FechaCompra` DATE NOT NULL,
  `TotalCompra` DOUBLE NOT NULL,
  `Estado` VARCHAR(30) NOT NULL COMMENT 'pendiente, pagada, recibida',
  PRIMARY KEY (`IdCompra`),
  INDEX `fk_COMPRA_PROVEEDOR1_idx` (`IdProveedor` ASC),
  INDEX `fk_COMPRA_EMPLEADO1_idx` (`IdEmpleado` ASC),
  CONSTRAINT `fk_COMPRA_PROVEEDOR1`
    FOREIGN KEY (`IdProveedor`)
    REFERENCES `db_tecnovera`.`PROVEEDOR` (`IdProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMPRA_EMPLEADO1`
    FOREIGN KEY (`IdEmpleado`)
    REFERENCES `db_tecnovera`.`EMPLEADO` (`IdEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_tecnovera`.`DETALLE_COMPRA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tecnovera`.`DETALLE_COMPRA`;
CREATE TABLE IF NOT EXISTS `db_tecnovera`.`DETALLE_COMPRA` (
  `IdDetalleCompra` INT NOT NULL AUTO_INCREMENT,
  `IdCompra` INT NOT NULL,
  `IdProducto` INT NOT NULL,
  `CantidadCompra` INT NOT NULL,
  `CostoUnitario` DOUBLE NOT NULL,
  `SubtotalCompra` DOUBLE NOT NULL,
  PRIMARY KEY (`IdDetalleCompra`),
  INDEX `fk_DETALLE_COMPRA_COMPRA1_idx` (`IdCompra` ASC),
  INDEX `fk_DETALLE_COMPRA_PRODUCTO1_idx` (`IdProducto` ASC),
  CONSTRAINT `fk_DETALLE_COMPRA_COMPRA1`
    FOREIGN KEY (`IdCompra`)
    REFERENCES `db_tecnovera`.`COMPRA` (`IdCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLE_COMPRA_PRODUCTO1`
    FOREIGN KEY (`IdProducto`)
    REFERENCES `db_tecnovera`.`PRODUCTO` (`IdProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_tecnovera`.`USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tecnovera`.`USUARIO`;
CREATE TABLE IF NOT EXISTS `db_tecnovera`.`USUARIO` (
  `IdUsuario` INT NOT NULL AUTO_INCREMENT,
  `Codigo` VARCHAR(15) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `IdCargo` INT NOT NULL,
  `EstadoUsuario` TINYINT(1) NOT NULL,
  PRIMARY KEY (`IdUsuario`),
  INDEX `fk_USUARIO_CARGO1_idx` (`IdCargo` ASC),
  CONSTRAINT `fk_USUARIO_CARGO1`
    FOREIGN KEY (`IdCargo`)
    REFERENCES `db_tecnovera`.`CARGO` (`IdCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_tecnovera`.`PEDIDO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tecnovera`.`PEDIDO`;
CREATE TABLE IF NOT EXISTS `db_tecnovera`.`PEDIDO` (
  `IdPedido` INT NOT NULL AUTO_INCREMENT,
  `IdCliente` INT NOT NULL,
  `FechaPedido` DATE NOT NULL,
  `TotalPedido` DOUBLE NOT NULL,
  `IdPago` INT NOT NULL,
  `IdEmpleado` INT NOT NULL,
  PRIMARY KEY (`IdPedido`),
  INDEX `fk_PEDIDO_CLIENTE_idx` (`IdCliente` ASC),
  INDEX `fk_PEDIDO_PAGO1_idx` (`IdPago` ASC),
  INDEX `fk_PEDIDO_EMPLEADO1_idx` (`IdEmpleado` ASC),
  CONSTRAINT `fk_PEDIDO_CLIENTE`
    FOREIGN KEY (`IdCliente`)
    REFERENCES `db_tecnovera`.`CLIENTE` (`IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_PAGO1`
    FOREIGN KEY (`IdPago`)
    REFERENCES `db_tecnovera`.`PAGO` (`IdPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_EMPLEADO1`
    FOREIGN KEY (`IdEmpleado`)
    REFERENCES `db_tecnovera`.`EMPLEADO` (`IdEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_tecnovera`.`DETALLE_PEDIDO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tecnovera`.`DETALLE_PEDIDO`;
CREATE TABLE IF NOT EXISTS `db_tecnovera`.`DETALLE_PEDIDO` (
  `IdDetallePedido` INT NOT NULL AUTO_INCREMENT,
  `IdPedido` INT NOT NULL,
  `IdProducto` INT NOT NULL,
  `CantidadPedido` INT NOT NULL,
  `PrecioUnitario` DOUBLE NOT NULL,
  `SubTotalPedido` DOUBLE NOT NULL,
  PRIMARY KEY (`IdDetallePedido`),
  INDEX `fk_DETALLE_PEDIDO_PEDIDO1_idx` (`IdPedido` ASC),
  INDEX `fk_DETALLE_PEDIDO_PRODUCTO1_idx` (`IdProducto` ASC),
  CONSTRAINT `fk_DETALLE_PEDIDO_PEDIDO1`
    FOREIGN KEY (`IdPedido`)
    REFERENCES `db_tecnovera`.`PEDIDO` (`IdPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLE_PEDIDO_PRODUCTO1`
    FOREIGN KEY (`IdProducto`)
    REFERENCES `db_tecnovera`.`PRODUCTO` (`IdProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;